# Development Dockerfile
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and yarn.lock
COPY package*.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 4000

# Start the Next.js development server
CMD ["yarn", "dev"]
